version: '3'

services:
  scylla:
    image: scylladb/scylla
    restart: unless-stopped
    ports:
      - "9042:9042"
    volumes:
      - scylladb:/var/lib/scylla

  rest_api:
    image: yonggan/fluffy_rest_api
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - scylla
    environment:
      - JWT_AUTH_SECRET=REPLACE_WITH_SECRET
      - SCYLLA_URI=scylla:9042

volumes:
  scylladb:
